### PR TITLE
Always use TypeHandler for parameters if available

### PR DESCRIPTION
**Pull request by matwilko**
Previously TypeHandlers could override the logic for built-in SQL data
types (int, byte, DateTime, etc.) when they were return values via
ITypeHandler.Parse, but ITypeHandler.SetValue was never called for these
types when used as parameters. Moved the typeHandlers.TryGetValue() call
up to make sure a type handler is always used if available.

Added tests to confirm standard behaviour is still working, and that ITypeHandler.SetValue is now called for built-in types.

### CODE REVIEW

**Comment by kartofeell** [comment]
I have applied changes from this PR on the latest master, and it works like a charm for me. TypeHandler.Parse and TypeHandler.Set

**Comment by kartofeell** [comment]
It would be great if this fix could get in. I guess there is not many conflicts to resolve, right?

**Comment by matwilko** [comment]
I would imagine not if you were able to simply apply the changes to the current master, however even then it is still a matter of Marc's time, since he needs to verify the PR before merging.
Functionality within Dapper may well have changed around this in the meantime though, it has been 11 months after all!

**Comment by NickCraver** [comment]
Do you mind rebasing this to current master so we can take a proper look and merge it in?

**Comment by matwilko** [comment]
Sure, I'll have a look this evening.

**Comment by NickCraver** [comment]
It looks like we can't actually pull this in due to comments mentioned on #339. It'll require some more digging to see if we can do this in a workable way - punting for the moment while we do some maintenance to make all future PRs easier though.

**Comment by nil4** [comment]
In https://github.com/StackExchange/dapper-dot-net/pull/339#issuecomment-148461888:

> Since we can't merge either - I'll consolidate this into #177 so we can track the issue in one place.

However, both issues are now closed despite not being resolved; @NickCraver consider reopening.

**Pull request closed without merging**
