### PR TITLE
Dapper.Contrib GetWhere implementation

### PR DESCRIPTION
**Pull request by majorsilence**
Retrieve data with custom where clause without writing sql.

### CODE REVIEW

**Comment by johandanforth** [comment]
Looks interesting. I would like to hear from a few others what they think before I pull this one in :)
So what do you guys think?

**Comment by mgravell** [comment]
Looks useful; code observations:

1. the `throw new DataException("GetWhere<T> must have param");` exception is vague and unclear - the problem is actually the lack of properties
2. it will be specific to particular SQL variants thanks to the `@` - that's a really awkward problem to work around, I realize
3. in some ways it would be nice if the `GetWhereAsync` could use an `await GetOpenConnectionAsync()`

**Comment by majorsilence** [comment]
For point 2 I have added a new Symbol property to ISqlAdapter.  The other option I can think of is adding a new GetWhere method to ISqlAdapter.

**Comment by mgravell** [comment]
Is it expected that external developers will implement ISqlAdapter? Or is
it intended to be internally provided only? Because if the former: this is
a compilation breaking change...

On 5 October 2015 at 19:46, Peter Gill <notifications@github.com> wrote:

> For point 2 I have added a new Symbol property to ISqlAdapter. The other
> option I can think of is adding a new GetWhere method to ISqlAdapter.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/pull/345#issuecomment-145628785>
> .
>



-- 
Regards,

Marc

**Comment by NickCraver** [comment]
I'm also curious about `ISqlAdapter`, but more concerned with what it will and won't support. For example, can I pass a list that translates to an `IN` clause? What about dates between? Greater than, less than? Like clauses? How about `IS NULL` and `IS NOT NULL`?

None of the above are supported, and we're edging into equals-only ORM generation land which IMO is better to leave out than to bring in extremely limited (and therefore confusing). I think to do it *well* we're really leaving Dapper's core goals and getting into pretty severe complication amongst each provider due to differences in many of these syntaxes across at least *one* of the platforms. From the practical usability standpoint, what would you pass in? Usually you'd use the same type as you'd deserialize from, but that's not really practical as they'd all be parameters in the WHERE clause - meaning you're making duplicated types (possibly anonymous) to do the query. I'm not sure that's significantly worse than SQL text alternative (what we're good at), but worth pointing out for real-world scenarios.

Thoughts from others?

**Comment by majorsilence** [comment]
I should probably rethink this.  @NickCraver has some good points that is affecting my team.  We use the current implementation of GetWhere but are left wanting many of the features listed but missing.

**Comment by johandanforth** [comment]
I'm not sure but I never thought ISqlAdapter was to be implemented by external developers. The interface can be useful for a few other issues though, like #336, where it can be used to build different select column clauses depending on sql-version. @NickCraver Could you please explain more what you mean with "we're edging into equals-only ORM generation land which IMO is better to leave out than to bring in extremely limited". I don't really fully understand (english is not my first language...), and I want to :)

**Comment by NickCraver** [comment]
@johandanforth by that I mean we don't support a ton of the *very common* query cases, much less anything really flexible here. It's really getting into full ORM territory. You simple can't pass an object and form a query - it comes down to that really. Unfortunately for any `WHERE`/`AND` statement needs the operator and 1 or more operands (for example a date range would be 2). In general that's getting into *much* heavier ORM territory and not really outside the goals of Dapper.

I'm speaking only for me here - but my thoughts are that *if* we go down this route of offering an interface like this at all (I don't think we should), then we need to at the very minimum handle all of the common query cases, `<`, `>`, `=`, `LIKE`, `IS NULL`, `IN`, `BETWEEN`, etc. - and simply can't be done with the pass-in-an-object model that's so lightweight. and pervasive in Dapper today. 

It's a sliding spectrum of "what should be automatic?" to "what can we generate?". At the end of the day anything is building a string for a query and throwing it at SQL. If it requires so much work to do operators, etc. then at what point is it better to just write the SQL query (how Dapper works today)? I'd argue that happens well before it's worth having an interface like this. I think that if a user's goals are much more towards the generation end of things, then Dapper simply isn't the best tool for the job and another ORM is likely a much better fit.

**Comment by tms** [comment]
I agree with @NickCraver, it seems like a dark road to go down. If this is something that a lot of people might find useful, maybe another option would be to extend on `SqlBuilder` with some helpers to generate common templates? Then you'd have more access to the flexibility of specifying your own SQL, but save some typing.

It's still likely to be provider-specific in some cases though, so it might not be appropriate for Dapper proper.

**Pull request closed without merging**
