### PR TITLE
SqlMapper global/default CommandTimeout

### PR DESCRIPTION
**Pull request by Irrational86**
The way this new property works is by looking at the nullable `commandTimeout` parameter passed to the `CommandDefinition` class, and if null, use the new `CommandTimeout` Setting.

Dapper works via Extension Methods, which are static, therefore not allowing instantiated versions to hold different values. I find that this is OK, given that the option to specify the Command Timeout is provided on each call to `Execute`, `ExecuteReader`, `Query`, and `QueryMultiple`.

An alternative, which I currently use, but do not like the additional layer is as follows:
- Create a new class which inherits from `DbConnection`
- Act as pass-thru on all of the overridable methods, except `CreateDbCommand` (which is more involved)
- In `CreateDbCommand`, hold the return value in a variable, modify the `CommandTimeout` property as desired, and return it
- *See sample class here: [DB Connection Class with default CommandTimeout](https://gist.github.com/176f853a25e00e9abc37.git)*

Additional discussion on Issue #282.

I hope this initial design helps pave the way for additional settings and features.

### CODE REVIEW

**Comment by Irrational86** [comment]
@mgravell  Thanks Marc!

**Comment by perragradeen** [comment]
How is this used?

Link is broken
See sample class here: DB Connection Class with default CommandTimeout

**Comment by perragradeen** [comment]
Found it ex.
     var items = connection.Query<MainItemForList>(query, param, commandTimeout: queryTimeoutInSeconds, buffered: false);

(from https://stackoverflow.com/questions/15683197/weird-timeout-issues-with-dapper-net/32524428#32524428)

**Comment by Irrational86** [comment]
@perragradeen Link above has been updated. The sample class explains how to subclass/inherit the `DbConnection` class in order to set a global timeout.

This Pull Request has already been merged into Dapper, so if you're using Dapper, you can simply set `SqlMapper.Settings.CommandTimeout = 60`. Then, all queries and commands executed via Dapper will have a timeout of 60 seconds (or whatever value you specify).

The more granular option, as you demonstrated above, is to specify the timeout on each query or command independently.

**Comment by perragradeen** [comment]
I cannot find "Settings" in the static Class Dapper.SqlMapper
Functions that exist are for example SetTypeName(...)

**Comment by Irrational86** [comment]
@perragradeen This pull requests is targeted for the 1.5.0 release of Dapper. If you use NuGet, you should be able to use the beta package (though betas are usually not recommended for production use): https://www.nuget.org/packages/Dapper.

**Comment by mgravell** [comment]
I should note that we're dogfooding the beta in production at
stackoverflow. Will review asap.

**Comment by NickCraver** [comment]
I *really* want to rename these, with a unit. e.g. `CommandTimeoutSeconds` It'd be a breaking change on the global, but less impactful on the param names (still breaking if they're specified in code due to optional). Maybe in a 2.0 release...

**Comment by Irrational86** [comment]
@NickCraver feel free to change it. I created the original PR, and since it's in beta, I am probably one of the very few using it.

**Comment by mgravell** [comment]
IMO: if this is only in the beta - we can do this.

On 15 December 2015 at 01:38, Nick Craver <notifications@github.com> wrote:

> I *really* want to rename these, with a unit. e.g. CommandTimeoutSeconds
> It'd be a breaking change on the global, but less impactful on the param
> names (still breaking if they're specified in code due to optional). Maybe
> in a 2.0 release...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/pull/284#issuecomment-164614131>
> .
>



-- 
Regards,

Marc

**Pull request merged**
