### PR TITLE
Added checks to make sure that arrays get the appropriate type when d…

### PR DESCRIPTION
**Pull request by joncloud**
…elete/insert/update is called.

### CODE REVIEW

**Comment by mgravell** [comment]
Not my area, but: looks good to me

**Comment by joncloud** [comment]
FYI i'm not sure what caused `Dapper.Tests.Contrib` to fail, but according to the output it looks like its using `1.0.0-rc2-16351` instead of `1.0.0-rc1-final`.  I was able to execute the tests locally, but it did skip the MySql tests.  Any thoughts?

**Comment by NickCraver** [comment]
Changed the build to not use unstable for now - kicking it for another try.

**Comment by johandanforth** [comment]
Quick browse at the code but it looks good. Jonathan I guess you ran into some probs with the old code?

Skickat från min Windows Phone
________________________________
Från: Marc Gravell<mailto:notifications@github.com>
Skickat: ‎2015-‎12-‎25 20:01
Till: StackExchange/dapper-dot-net<mailto:dapper-dot-net@noreply.github.com>
Ämne: Re: [dapper-dot-net] Added checks to make sure that arrays get the appropriate type when d… (#428)

Not my area, but: looks good to me
On 25 Dec 2015 6:53 p.m., "Jonathan Berube" <notifications@github.com>
wrote:

> …elete/insert/update is called.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/StackExchange/dapper-dot-net/pull/428
> Commit Summary
>
>    - Added checks to make sure that arrays get the appropriate type when
>    delete/insert/update is called.
>
> File Changes
>
>    - *M* Dapper.Contrib/SqlMapperExtensions.Async.cs
>    <https://github.com/StackExchange/dapper-dot-net/pull/428/files#diff-0>
>    (23)
>    - *M* Dapper.Contrib/SqlMapperExtensions.cs
>    <https://github.com/StackExchange/dapper-dot-net/pull/428/files#diff-1>
>    (23)
>    - *M* Dapper.Tests.Contrib/TestSuite.Async.cs
>    <https://github.com/StackExchange/dapper-dot-net/pull/428/files#diff-2>
>    (46)
>    - *M* Dapper.Tests.Contrib/TestSuite.cs
>    <https://github.com/StackExchange/dapper-dot-net/pull/428/files#diff-3>
>    (47)
>
> Patch Links:
>
>    - https://github.com/StackExchange/dapper-dot-net/pull/428.patch
>    - https://github.com/StackExchange/dapper-dot-net/pull/428.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/pull/428>.
>


---

**Comment by joncloud** [comment]
Yeah `GetGenericArguments` returned an empty array.

**Comment by NickCraver** [comment]
Thanks @joncloud :)

**Pull request merged**
