### PR TITLE
Upgrading platform monikers

### PR DESCRIPTION
**Pull request by sebastienros**
Haven't run the unit tests myself, hope the CI is doing it, but builds and create the nuget packages correctly using `dnu pack --configuration release`

### CODE REVIEW

**Comment by sebastienros** [comment]
The CI needs to use rc1 instead of beta-8 I am not sure if you set it in the AppVeyor configuration on in a local build script. You'll know better.

**Comment by NickCraver** [comment]
Checking the build - un momento

**Comment by NickCraver** [comment]
Info found (though even the ASP.Net team doesn't use the new CLI tools...so we'll see how they use Appveyor as well) - poking another build to run here.

**Comment by sebastienros** [comment]
Yeah !

**Comment by NickCraver** [comment]
Appveyor updated - and builds passed. Yanking this in - I'll work on porting the unit tests to xUnit next so we can get them setup much easier in the build and with local runners.

Thanks for the work!

Disclaimer: I'm not sure this moniker structure is "correct" either - but I agree it's more correct than the current. I want to see if we can grab any of @davidfowl's time on this sometime this week or next to actually make this a concrete example of the proper setup.

**Comment by sebastienros** [comment]
Well, @davidfowl was by my side when I did the PR, just pure chance, and I showed it to him for some feedback, he approved ;)

**Comment by NickCraver** [comment]
Ah excellent - nevermind then! Much appreciated all around. We'll get a NuGet build up when @mgravell wakes across the pond - I'll crack at the unit tests and see if I can get them working proper with the new setup.

**Comment by sebastienros** [comment]
I don't know how you intend to run the unit test on AppVeyor, but just in case you want to go with Sqlite, you need to know it's broken with Dapper right now on ~~dnx~~ dotnet until RC2, because Sqlite didn't like how you remove the `@` from the parameters. At least you can run these tests on deskptop clr.

**Comment by NickCraver** [comment]
I have to admit - I'm still confused here. The TFMs in the annoucement here: https://github.com/aspnet/Announcements/issues/98 mention the style used here: `dotnet5.x

**Comment by sebastienros** [comment]
I am confused, what is confusing you?

**Comment by NickCraver** [comment]
Oh I see now, the work to make the tooling match the latest announcement (the `netstandard` monikers) isn't done yet:
> NOTE: The netstandard TFM does not work in packages as yet. It's still implemented as dotnet. Please follow the issues for more details and progress updates.

I (wrongly) assumed that'd be in place before the announcement and everyone jumping in :-/ Is there any ETA on that, since it'll be another round of changes? It's the way unit tests and such are picked up, so that'd be handy info.

**Comment by davidfowl** [comment]
Working on it. 😀

**Comment by sebastienros** [comment]
I used 1.2 because you were targeting `dnx451` previously and I didn't want to change that if that was on purpose. Also it compiled fine for me, and on the CI. I have core rc1-final locally. If you want to bump to 5.4 then it's up to you.

**Comment by mgravell** [comment]
I'm very confused why it didn't compile locally - either in the IDE or via `dnu pack`. I'll try pushing a rc1 build that targets 5.2 to appveyor

**Comment by mgravell** [comment]
The CI server seems to agree with me: https://ci.appveyor.com/project/StackExchange/dapper-dot-net-27k3h/build/1.0.103

**Comment by NickCraver** [comment]
I also can't build anymore on 5.2...though I could when this was pushed. I think some packages have changed their builds underneath and this now breaks. I think SQL Client's port on CoreCLR needing new items that aren't currently in managed code will ultimately dictate that we stay on 5.4 anyway, so I'd say let's stick with this setup and see if we have any need for a build between...which I don't think we do.

**Pull request merged**
