### PR TITLE
A full CoreCLR/DNX friendly conversion

### PR DESCRIPTION
**Pull request by NickCraver**
This eliminates the dual solutions and brings Contrib into the project.json fold.
- Tests are ported to xUnit though SQLite is disabled on DNX due to Issue #375 (Interop loads fail in the VS runner and  params are busted regardless).
- Projects are consolidated down to what's currently possible with project.json.
- Contrib moved to: `Dapper.Contrib` and `Dapper.Tests.Contrib` (so tests appear at the end, no other reason vs. `Dapper.Contrib.Tests`)
- EF moved to: `Dapper.EntityFramework(.StrongName)`
- Rainbow moved to: `Dapper.Rainbow`
- SqlBuilder moved to: `Dapper.SqlBuilder`
- Packages are removed since it's not current-tooling friendly to keep them (nor was it using them).
- xUnit implemented in Contrib via abstracts - this allow us to very quickly add any database provider to the rig in a very concise way.
- Contrib unit tests fixed in various places - they were not parallel-runner friendly
- Nuspecs removed, since they aren't used anymore (to eliminate confusion)
- Removed speed tests for libraries that aren't on current versions of .Net (what would we be comparing?)
- Perf tests moved to `Dapper.Tests` (consolidation from `Dapper.DNX.Tests`), but aren't activated yet (no define)

### CODE REVIEW

**Comment by johandanforth** [comment]
Massive! :)

**Comment by NickCraver** [comment]
Side notes for others: ^ I updated the Appveyor builds to run tests now, once we're stable there I'll commit an appveyor.yml. Bonus: we can run MySQL and Postgres tests there, meaning the core library and contrib can test against many platforms via abstract-base test suites. See Contrib in the commit for how I'm already doing this.

**Comment by mgravell** [comment]
Looks great from here

**Comment by NickCraver** [comment]
@mgravell thanks for the eyes! I'll get the other good PRs merged in and try and get MySQL/Postgres tests working on Appveyor...those would be awesome to get many issues fixed here and be our workhorse. First though, I'll get them working locally.

**Comment by alexeyfadeev** [comment]
Project is no more compatible with Visual Studio 2012, I get right?

**Comment by mgravell** [comment]
@alexeyfadeev The sln right now is aimed at the core-clr tooling. I don't know if this is available on VS2012, but the command-line tools to build/pack/etc are freely available. For a walkthrough of how to do this: http://blog.marcgravell.com/2015/11/the-road-to-dnx-part-1.html (and 2/3), but essentially it boils down to:

    git clone https://github.com/StackExchange/dapper-dot-net.git
    cd dapper-dot-net\Dapper
    dnu restore
    dnu build

**Comment by alexeyfadeev** [comment]
Thanks, I'll try

**Pull request merged**
