### PR TITLE
Key Data Type other than int and writable key (e.g. Guid)

### PR DESCRIPTION
**Pull request by jd4u**
- IsKeyWriteable to return default value
- Insert<T,TKey> method
- ISqlAdapter.Insert<TKey> returns TKey
- SqlServerAdapter.Insert<TKey> (Set Key value only if writeable)
- PostgressAdapter.Insert<TKey> (Set Key value only if writeable)
- Updated KeyAttribute to support AllowWrite property
- Tests for Generic with Int64 and Guid datatype.

### CODE REVIEW

**Comment by johandanforth** [comment]
@jd4u & @majorsilence Have you done any more work around this and support for keys other than integers? As long as it doesn't break existing interfaces I think we should include it.

**Comment by majorsilence** [comment]
I have a cleaned up copy at https://github.com/majorsilence/dapper-dot-net/commits/KeyDataType that I occasionally rebase.

I have been using this for about a year and have not noticed any problems.

**Comment by johandanforth** [comment]
Good. I'll try to get a good look at it this weekend.

________________________________
Från: Peter Gill<mailto:notifications@github.com>
Skickat: ‎2015-‎06-‎11 12:03
Till: StackExchange/dapper-dot-net<mailto:dapper-dot-net@noreply.github.com>
Kopia: Johan Danforth<mailto:johan_danforth@hotmail.com>
Ämne: Re: [dapper-dot-net] Key Data Type other than int and writable key (e.g. Guid) (#107)

I have a cleaned up copy at https://github.com/majorsilence/dapper-dot-net/commits/KeyDataType that I occasionally rebase.

I have been using this for about a year and have not noticed any problems.

---

**Comment by majorsilence** [comment]
I have a new branch https://github.com/majorsilence/dapper-dot-net/commits/KeyDataType2 that I am using to do my work on this change.  It is currently only rebased  as of June 11.  I was doing some work last night to fix some test failures.

I'll need to rebase again and fix some problems.

@jd4u Currently the TestGeneric.InsertGetUpdate test is failing. I am not as familiar with the changes as you.  Would you be wiling to review the above branch to see if I overlooked/broke something from your original changes.

The code below fails with a "Entity must have at least one [Key] property" message.
```c#
 connection.Get<IPerson<Int64>>(id);
```

**Comment by NickCraver** [comment]
I think the `TKey Insert<TKey>` is dead on, and we need to integrate this piece in a non-breaking fashion as discussed in #352. I'm closing this out since we'll merge that one soon - but the functionality is coming.

**Pull request closed without merging**
