### PR TITLE
Fix for issue #361

### PR DESCRIPTION
**Pull request by johandanforth**

### CODE REVIEW

**Comment by johandanforth** [comment]
ping @NickCraver and @mgravell any thoughts on these Contrib pulls I made?

**Comment by mgravell** [comment]
Sorry, life got crazy; fix looks fine; doesn't merge at the moment; do you want to update to latest, or should I try to do a "pull, reapply, merge and hope it comes out alright" ?

**Comment by johandanforth** [comment]
Again mate, please go ahead as I'm still not up to speed with the new environment :)

**Comment by NickCraver** [comment]
Manual merge complete - thanks!

**Comment by johandanforth** [comment]
Awesome

**Pull request merged**
